### ISSUE TITLE
Arduino Uno R3 + inAir9: unrecognized transceiver

### ISSUE THREAD

**Issue by pdominique** [CongducPham/LowCostLoRaGw#11]
I followed the instructions in the pdf tutorials to setup a GW with an inAir9 with a Raspberry Pi 2. The GW seems to work just fine (at least there's no error when I start it) but the node doesn't. I get an "Unrecognized Transceiver" error.

I'm using an Arduino UNO R3 and an inAir9 module and I used the following diagram to wire everything with the ICSP pins: ![](http://gammon.com.au/images/ArduinoUno_R3_Pinouts.png)

|inAir9|UNO|
|---|---|
|VCC|3.3V|
|CLK|SCK (ICSP)|
|MISO|MISO (ICSP)|
|MOSI|MOSI (ICSP)|
|GND|GND|
|CS|Digital Pin 2 (Interrupt 0)|

I'm new to all of this, is my wiring ok?

EDIT: I tried with the temp and simple_temp sketches and the only thing I changed is the band because I'm in Canada.

**Comment by CongducPham** [comment]
The pin assignment is correct. Could you check with a voltmeter that you 
do have 3.3V supplied to the radio? Check again the SPI pins, because I 
don't see why it is not working, apart from an error when wiring the pins.

regards,

Le 16/05/16 14:36, pdominique a écrit :
>
> I followed the instructions in the pdf tutorials to setup a GW with an 
> inAir9 with a Raspberry Pi 2. The GW seems to work just fine (at least 
> there's no error when I start it) but the node doesn't. I get an 
> "Unrecognized Transceiver" error.
>
> I'm using an Arduino UNO R3 and an inAir9 module and I used the 
> following diagram to wire everything with the ICSP pins: 
> <https://camo.githubusercontent.com/3a52f84c2820d093cf4a6913ac6192e4aa568f08/687474703a2f2f67616d6d6f6e2e636f6d2e61752f696d616765732f41726475696e6f556e6f5f52335f50696e6f7574732e706e67>
>
> inAir9 	UNO
> VCC 	3.3V
> CLK 	SCK (ICSP)
> MISO 	MISO (ICSP)
> MOSI 	MOSI (ICSP)
> GND 	GND
> CS 	Digital Pin 2 (Interrupt 0)
>
> I'm new to all of this, is my wiring ok?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/CongducPham/LowCostLoRaGw/issues/11>
>

C. Pham.


-- 
|------------ Congduc PHAM - Professor --------------------------|
|  LIUPPA - Equipe T2I              |         U.P.P.A. Pau       |
|  http://liuppa.univ-pau.fr/       |   http://www.univ-pau.fr   |
|----------------------------------------------------------------|
|UPPA, LIUPPA laboratory, UFR Sciences et Techniques             |
|Avenue de l'Université - BP 1155                                |
|64013 PAU CEDEX, FRANCE                                         |
|                                                                |
|phone:  [33] (0) 5 59 40 75 94                                  |
|fax:    [33] (0) 5 59 40 76 54                                  |
|Congduc.Pham@univ-pau.fr       http://www.univ-pau.fr/~cpham    |
|----------------------------------------------------------------|

**Comment by pdominique** [comment]
Thanks, it must have been a bad cable because I just rewired everything and it works as expected now. I had to change line 244 in the simple temp example because channel selection is hardcoded for band 868:

```
e = sx1272.setChannel(CH_10_868);
```

**Comment by CongducPham** [comment]
Great!

I will modified simple temp to check for the band, just as in 
Arduino_LoRa_temp code.

Le 17/05/2016 14:45, pdominique a écrit :
>
> Thanks, it must have been a bad cable because I just rewired 
> everything and it works as expected now. I had to change line 244 in 
> the simple temp example because channel selection is hardcoded for 
> band 868:
>
> |e = sx1272.setChannel(CH_10_868); |
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/CongducPham/LowCostLoRaGw/issues/11#issuecomment-219706262>
>

C. Pham.


-- 
|------------ Congduc PHAM - Professor --------------------------|
|  LIUPPA - Equipe T2I              |         U.P.P.A. Pau       |
|  http://liuppa.univ-pau.fr/       |   http://www.univ-pau.fr   |
|----------------------------------------------------------------|
|UPPA, LIUPPA laboratory, UFR Sciences et Techniques             |
|Avenue de l'Université - BP 1155                                |
|64013 PAU CEDEX, FRANCE                                         |
|                                                                |
|phone:  [33] (0) 5 59 40 75 94                                  |
|fax:    [33] (0) 5 59 40 76 54                                  |
|Congduc.Pham@univ-pau.fr       http://www.univ-pau.fr/~cpham    |
|----------------------------------------------------------------|
