### ISSUE TITLE
Arduino 1MHz

### ISSUE THREAD

**Issue by Samuel-ZDM** [CongducPham/LowCostLoRaGw#290]
Hello!

I'm using an Atmega328 with 1MHz with RFM95, but I can't send a message to the gateway.
My device sends the first message and then no longer sends it.
I am using the ABP example to send to TTN.

Can you help me?

**Comment by CongducPham** [comment]
It might come from a timing problem with the 1MHz board. In LMIC there are macros to define how many tick/seconds you are considering. It is defined in oslmic I think.

**Comment by Samuel-ZDM** [comment]
Ok.
Do I need to change the values for these macros?
Is there a formula for finding the right values?

**Comment by CongducPham** [comment]
Well I don't remember exactly but it LMIC ticks are based on micros() function, which in turn is based on the frequency of your board. See here for some explanation: https://ucexperiment.wordpress.com/2012/03/17/examination-of-the-arduino-micros-function/. So the goal is to scale correctly so that you get about 16us per os tick. Hope that helps

**Comment by Samuel-ZDM** [comment]
Thank you very much!
I'll try to fix this!
